language: java
sudo: true
dist: trusty
jdk:
  - oraclejdk9
services:
  - 'docker'
before_install:
  - chmod +x mvnw

# Build the application.
script:
  - 'make build'
  - 'make image'

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# filled you need to either use `travis`' cli
# and then `travis set ..` or go to the travis
# page of your repository and then change the
# environment in the settings panel.
after_success:
  - 'make push-image'
