version: '3'
services:
  localstack:
    healthcheck:
      test: ["CMD-SHELL", "/health-check-scripts/aws-services-healthcheck.sh || exit 1"]
      interval: 2s
    image: localstack/localstack:0.11.2
    container_name: localstack
    ports:
      - '4569:4569' # DynamoDB
      - '4576:4576' # SQS
      - '8055:8081' # Localstack UI
    environment:
      - SERVICES=dynamodb,sqs
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=accessKey
      - AWS_SECRET_ACCESS_KEY=secretKey
      - AWS_REGION=sa-east-1
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./src/main/resources/aws/services:/docker-entrypoint-initaws.d"
      - "./src/main/resources/aws/healthcheck:/health-check-scripts"
      - '/var/run/docker.sock:/var/run/docker.sock'

  locations-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locations-service
    environment:
      - AMAZON_PROPS=export AWS_ACCESS_KEY_ID=accessKey AWS_SECRET_ACCESS_KEY=secretKey AWS_REGION=sa-east-1
      - APPLICATION_ARGS=-Dspring.profiles.active=local -DVEHICLE_QUEUE_URL=http://localstack:4576/queue/creation-vehicle-location-queue -DDYNAMO_ENDPOINT=http://localstack:4569 -DVEHICLE_QUEUE_ENDPOINT=http://localstack:4576
    ports:
      - "8080:8080"
    links:
      - localstack